### GET request to example server
#GET https://examples.http-client.intellij.net/get
#    ?generated-in=PyCharm
#
###

# curl -X POST -H "Content-Type: multipart/form-data" -F "file=@/path/to/file.txt" https://api.example.com/upload
POST http://127.0.0.1:5000/predict
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="cat_1.jpg"

< cat_1.jpg
--WebAppBoundary--

###

# curl -X POST -H "Content-Type: multipart/form-data" -F "file=@/path/to/file.txt" https://api.example.com/upload
POST http://127.0.0.1:5000/predict
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="cat_2.jpg"

< cat_2.jpg
--WebAppBoundary--

###

